---
# This file updates the Splunk Universal Forwarders

- name: 1st Register Splunk Status
  command: /opt/splunkforwarder/bin/splunk status
  register: status
  ignore_errors: true

- name: Stop Splunk
  command: /opt/splunkforwarder/bin/splunk stop
  when:
    - status.stdout != "splunkd is not running."

- name: 2nd Register Splunk Status
  command: /opt/splunkforwarder/bin/splunk status
  register: status
  ignore_errors: true

- name: (CentOS) Upgrade Splunk Forwarder.
  yum:
    name: "{{ splunkf_package_location }}/{{ splunkf_package_rpm }}"
    state: present
  when:
    - ansible_distribution == "CentOS"
    - status.stdout == "splunkd is not running."
  notify:
    - Start Splunk and Accept License

- name: (Ubuntu) Upgrade Splunk Forwarder.
  apt:
    deb: "{{ splunkf_package_location }}/{{ splunkf_package_deb }}"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - status.stdout == "splunkd is not running."
  notify:
    - Start Splunk and Accept License
    
- name: Change Splunk Permissions
  file: 
    path: /opt/splunkforwarder
    state: directory
    recurse: yes
    owner: splunk
    group: splunk
