---
# file: site_splunk_forwarder.yml

- name: Apply common configuration to baseline nodes
  hosts: ansible-test-host2 
  remote_user: inolan
  become: yes
  become_user: root
  gather_facts: true
  roles:
    - splunk-forwarder

