---
# file: site_splunk_forwarder.yml

- name: Apply common configuration to baseline nodes
  hosts: archive-test-host 
  remote_user: inolan
  become: yes
  become_user: root
  gather_facts: true
  roles:
    - splunk-forwarder

