---
# file: roles/splunk-forwarder/tasks/main.yml

- name: Check all port numbers are accessible from current host
  wait_for:
    port: 8089
    state: stopped         # Port should be open
    delay: 0               # No wait before first check (sec)
    timeout: 1             # Stop checking after timeout (sec)
    msg: "Port 8089 is busy. Splunk may already be installed. Aborting."

- name: (CentOS) Install Splunk Forwarder.
  yum:
    name: "{{ splunkf_package_location }}/{{ splunkf_package_rpm }}"
    state: present
  when:
    - ansible_distribution == "CentOS"
  notify:
    - accept splunk license
    - enable splunk start-on-boot
    - add splunk forwarding server
    - add splunk deployment server
    - restart splunk forwarder

- name: (Ubuntu) Install Splunk Forwarder.
  apt:
    deb: "{{ splunkf_package_location }}/{{ splunkf_package_deb }}"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
  notify:
    - accept splunk license
    - enable splunk start-on-boot
    - add splunk forwarding server
    - add splunk deployment server
    - restart splunk forwarder

- name: Create Splunk user seed file.
  template:
    src: opt_splunkforwarder_etc_system_local_user-seed.conf
    dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
  notify:
    - restart splunk forwarder

- name: Change Splunk Permissions
  file: 
    path: /opt/splunkforwarder
    state: directory
    recurse: yes
    owner: splunk
    group: splunk
