---
# file: roles/common/handlers/main.yml

- name: restart network
  systemd:
    name: network
    state: restarted

- name: restart iptables
  systemd:
    name: iptables
    state: restarted
    
- name: restart iptables6
  systemd:
    name: ip6tables
    state: restarted

- name: restart netfilter
  systemd:
    name: netfilter-persistent
    state: restarted
    
- name: restart sshd
  systemd:
    name: sshd
    state: restarted


- name: restart ntp
  systemd:
    name: ntp
    state: restarted

- name: restart ntpd
  systemd:
    name: ntpd
    state: restarted
