---
# This file hardens Centos 7 servers

# Upadates

- name: Install All Non-Kernel Updates
  yum: 
    name: "*" 
    exclude: kernel*
    state: latest

- name: Install Kernel Updates
  yum: 
    name: "kernel*" 
    state: latest
  when: update_kernel|bool == true
  notify: Restart Machine

- name: Remove Packages
  yum:
    name: '{{ item }}'
    state: absent
  with_flattened:
    - '{{remove_unwanted_packages}}'

# System Settings – File Permissions and Masks

- name: Restrict Partition Mount Options / 
  mount:
    path: "/"
    src: "/dev/mapper/centos-root"
    fstype: "xfs"
    state: mounted
  notify: Restart Machine

- name: Restrict Partition Mount Options /boot 
  mount:
    path: "/boot"
    src: "none"
    fstype: "xfs"
    state: mounted
    opts: "rw, nodev, nosuid, noexec"
  notify: Restart Machine

- name: Restrict Partition Mount Options /home 
  mount:
    path: "/home"
    src: "/dev/mapper/centos-home"
    fstype: "xfs"
    state: mounted
    opts: "rw, nodev, nosuid"
  notify: Restart Machine

- name: Restrict Partition Mount Options /tmp 
  mount:
    path: "/tmp"
    src: "/dev/mapper/centos-tmp"
    fstype: "tmpfs"
    state: mounted
    opts: "rw, nodev, nosuid, noexec"
  notify: Restart Machine

- name: Restrict Partition Mount Options /var/tmp 
  mount:
    path: "/var/tmp"
    src: "/dev/mapper/centos-var_tmp"
    fstype: "none"
    state: mounted
    opts: "rw, nodev, nosuid, noexec, bind"
  notify: Restart Machine

- name: Restrict Partition Mount Options /var 
  mount:
    path: "/var"
    src: "/dev/mapper/centos-var"
    fstype: "xfs"
    state: mounted
    opts: "rw, nosuid,"
  notify: Restart Machine

- name: Restrict Partition Mount Options /var/log 
  mount:
    path: "/var/log"
    src: "/dev/mapper/centos-var_log"
    fstype: "xfs"
    state: mounted
    opts: "rw, nodev, nosuid, noexec"
  notify: Restart Machine

- name: Restrict Partition Mount Options /var/log/audit 
  mount:
    path: "/var/log/audit"
    src: "/dev/mapper/centos-var_log_audit"
    fstype: "xfs"
    state: mounted
    opts: "rw, nodev, nosuid, noexec"
  notify: Restart Machine

- name: Restrict Partition Mount Options /dev/shm 
  mount:
    path: "/dev/shm"
    src: "none"
    fstype: "tmpfs"
    state: mounted
    opts: "rw, nodev,nosuid,noexec"
  notify: Restart Machine

- name: Restrict Partition Mount Options /var/www
  mount:
    path: "/var/www"
    src: "/dev/mapper/centos-var_www"
    fstype: "xfs"
    state: mounted
    opts: "nodev,nosuid,bind"
  notify: Restart Machine

- name: Restrict Partition Mount Options /proc
  mount:
    path: "/proc"
    src: "none"
    fstype: "proc"
    state: mounted
    opts: "rw, hideip=2"
  notify: Restart Machine
  
- name: Restrict Dynamic Mounting and Unmounting of Filesystems
  template:
    src: etc_modprobe.d_hardening.conf
    dest: /etc/modprobe.d/hardening.conf
    
- name: Restrict Programs from Dangerous Execution Patterns
  template:
    src: etc_sysctl.conf
    dest: /etc/sysctl.conf
  notify:
    - load sysctl settings
