---
# This file hardens Centos 7 servers

- name: Install All Non-Kernel Updates
  yum: 
    name: "*" 
    exclude: kernel*
    state: latest

- name: Install Kernel Updates
  yum: 
    name: "kernel*" 
    state: latest
  when: update_kernel|bool == true
  notify: Restart Machine

- name: Remove Packages
  yum:
    name: '{{ item }}'
    state: absent
  with_flattened:
    - '{{remove_unwanted_packages}}'
