---
# file: roles/common/tasks/main.yml

# network

- import_tasks: network_centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- import_tasks: network_ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "16"

# iptables

- import_tasks: iptables_centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    
- import_tasks: iptables_ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "16"

# ntp
  
- import_tasks: ntp_centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- import_tasks: ntp_ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "16"
