---
# file: roles/_common/tasks/splunk-forwarder.yml

- name: Check If Splunk is Already Installed
  yum:
    name: splunk
    state: present
  register: splunk_installed
  ignore_errors: true

- name: (CentOS) Install Splunk Forwarder.
  yum:
    name: "{{ splunkf_package_location }}/{{ splunkf_package_rpm }}"
    state: present
  when:
    - ansible_distribution == "CentOS"
    - splunk_installed is failed
  notify:
    - accept splunk license
    - enable splunk start-on-boot
    - add splunk forwarding server
    - add splunk deployment server
    - restart splunk forwarder

- name: (Ubuntu) Install Splunk Forwarder.
  apt:
    deb: "{{ splunkf_package_location }}/{{ splunkf_package_deb }}"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - splunk_installed is failed
  notify:
    - accept splunk license
    - enable splunk start-on-boot
    - add splunk forwarding server
    - add splunk deployment server
    - restart splunk forwarder

- name: Create Splunk user seed file.
  template:
    src: opt_splunkforwarder_etc_system_local_user-seed.conf
    dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
  when: 
    - splunk_installed is failed
  notify:
    - restart splunk forwarder

- name: Change Splunk Permissions
  file: 
    path: /opt/splunkforwarder
    state: directory
    recurse: yes
    owner: splunk
    group: splunk
